import { validatedEnv } from "./validateEnv";

export const env = {
  APP_URL: validatedEnv.NEXT_PUBLIC_APP_URL,
  FIREBASE: {
    API_KEY: validatedEnv.NEXT_PUBLIC_FIREBASE_API_KEY,
    AUTH_DOMAIN: validatedEnv.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN,
    PROJECT_ID: validatedEnv.NEXT_PUBLIC_FIREBASE_PROJECT_ID,
    STORAGE_BUCKET: validatedEnv.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET,
    MESSAGING_SENDER_ID: validatedEnv.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID,
    APP_ID: validatedEnv.NEXT_PUBLIC_FIREBASE_APP_ID,
    MEASUREMENT_ID: validatedEnv.NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID,
  },
  EMAILJS: {
    SERVICE_ID: validatedEnv.NEXT_PUBLIC_EMAILJS_SERVICE_ID,
    TEMPLATE_ID: validatedEnv.NEXT_PUBLIC_EMAILJS_TEMPLATE_ID,
    PUBLIC_KEY: validatedEnv.NEXT_PUBLIC_EMAILJS_PUBLIC_KEY,
  },
} as const;
